### PR TITLE
Update fzf's release page

### PR DESCRIPTION
**Pull request by jeromepin**
Since 0.24.0, new releases are available only in junegunn/fzf/releases.

### CODE REVIEW

**Comment by kompiro** [comment]
@jeromepin 

Thanks for your contribution!
I think this plugin may supports old versions because asdf supports to stick tool version.
So I'll try to merge the list of releases.

Do you have any idea to merge the lists?

**Comment by jeromepin** [comment]
Hey @kompiro,

I tried to have it fetch both repos in order to have the full history of versions. I'm not very experienced with bash scripting, so tell what you think.

It appears we don't have to modify the install script because all archives are downloaded from the same repo 🤷‍♂️ 🥳

**Comment by jeromepin** [comment]
Hi @kompiro 👋 Do you have any update on this ?

**Comment by kompiro** [comment]
Wow, thanks for your contribution!

**Pull request merged**
